# Generated by Django 5.0.2 on 2024-09-23 12:54

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=jobs.models.get_default_start_date)),
                ('end_date', models.DateField(default=jobs.models.get_default_end_date)),
                ('requirements', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
